// src/components/Video.jsx
import { useState } from "react";

export const ReactExample = function ReactExample() {
  const [altColours, setAltColours] = useState(false);

  return (
    <section
      className={`react-container${altColours ? " react-container-alt" : ""}`}
    >
      <h2>Актуальные новости киноиндустрии</h2>
      <div className="video-container">
        <iframe
          width="560"
          height="315"
          src="https://www.youtube-nocookie.com/embed/SbMBZB-R-8E"
          title="Актуальные новости киноиндустрии"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        />
      </div>
      <button
        className={`react-button${altColours ? " react-button-alt" : ""}`}
        onClick={() => {
          setAltColours(!altColours);
        }}
      >
        <span className="screen-reader-text">Toggle colours</span>
      </button>
    </section>
  );
};

export default ReactExample;

// src/components/Video.svelte
<script lang='ts'>
  export let altColours = false
  export let hash: string = ''
  export let title: string = ''

  const youtube = 'https://www.youtube-nocookie.com/embed/'
</script>

<section class={`container${altColours ? " container-alt" : ""}`}>
  <h2>{title}</h2>
  <div class="video-container">
    <iframe
      title={title}
      width="560"
      height="315"
      src={youtube + hash}
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen
    />
  </div>
  <button
    class={`button${altColours ? " button-alt" : ""}`}
    on:click={() => {
      altColours = !altColours;
    }}><span class="screen-reader-text">Toggle colours</span></button
  >
</section>
